# Generated by Django 3.2.3 on 2021-05-23 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='seires',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.series'),
            preserve_default=False,
        ),
    ]
