# Generated by Django 3.2.3 on 2021-05-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_rate_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_img',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
