# Generated by Django 3.2.3 on 2021-05-23 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rate_seires'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='seires',
            new_name='series',
        ),
    ]
