# Generated by Django 3.2.3 on 2021-05-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_user_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_img',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
